name: Test k8s mode
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: linux-arm64-npu-1-k8smode
    container:
      image: quay.io/ascend/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          echo hello
      - run: sleep 30000
