name: Test k8s mode v5
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: linux-arm64-npu-1-k8smode-v5
    container:
      image: quay.io/ascend/cann:latest
      
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
      - run: sleep 30000
