name: Sep runs-on image
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: sep-runson-image
    container:
      image: quay.io/ascend/cann:latest
    steps:
      - name: Show NPU info
        run: |
          npu-smi info
