name: Sep runs-on image -v2
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: sep-runson-image-2
    container:
      image: quay.io/ascend/cann:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Show NPU info
        run: |
          echo hello
