name: Show npu resource
on:
  workflow_dispatch:
jobs:
  jobs_npu1:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest

    steps:
      - name: Show NPU info
        run: |
          npu-smi info

