name: Test NPU
on:
  workflow_dispatch:
jobs:
  jobs_npu1:
    runs-on: linux-arm64-npu-1
    container:
      image: ascendai/cann:latest

    steps:
      - name: Show NPU info
        run: |
          npu-smi info
  jobs_npu2:
    runs-on: linux-arm64-npu-2
    container:
      image: ascendai/cann:latest

    steps:
      - name: Show NPU info
        run: |
          npu-smi info
